<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dts</string>
		<string>dtsi</string>
	</array>
	<key>name</key>
	<string>Devicetree</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Multiline Comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.devicetree</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Version I.D.</string>
			<key>match</key>
			<string>^/dts-[a-z0-9]*/;$</string>
			<key>name</key>
			<string>support.constant.file-version.devicetree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.devicetree</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\#include (.*)</string>
			<key>name</key>
			<string>keyword.standard.devicetree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.macro.name.devicetree</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.macro.value.devicetree</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\#define\s([^\s]*)\s(.*)</string>
			<key>name</key>
			<string>keyword.standard.define.devicetree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.node.devicetree</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.node-name.node.devicetree</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.unit-address.node.devicetree</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.unit-address.node.devicetree</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Devicetree Node, page 43</string>
			<key>match</key>
			<string>\b([A-Za-z0-9]*:\s)?([A-Za-z0-9\_-]*)(\@)?([A-Za-z0-9\_-]*)\s*\{</string>
			<key>name</key>
			<string>node.devicetree</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.label.node.devicetree</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.property-name.devicetree</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Property Definition</string>
			<key>match</key>
			<string>\b([A-Za-z0-9]*:\s)?([A-Za-z0-9\,\_\-]*)\s?=.*;</string>
			<key>name</key>
			<string>property-definition.devicetree</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\#.*$)</string>
			<key>name</key>
			<string>comment.line.number-sign.devicetree</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Standard Properties</string>
			<key>match</key>
			<string>(?i)\b(compatible|model|phandle|status|\#address-cells|\#size-cells|reg|virtual-reg|ranges|dma-ranges|device_type)(?=$|[\ \t,;="&amp;()/:])</string>
			<key>name</key>
			<string>variable.language.devicetree</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((0x)?[0-9A-Fa-f]*)</string>
					<key>name</key>
					<string>constant.numeric.devicetree</string>
				</dict>
			</array>
		</dict>
		<key>quote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.devicetree</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.devicetree</string>
	<key>uuid</key>
	<string>f8106bbd-6378-40f2-b68e-d374441a0b9d</string>
</dict>
</plist>
